# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy
defaults:
  run:
    working-directory: frontend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: cd frontend
    - run: yarn install
    - run: yarn build
    - run: yarn deploy
